### ISSUE TITLE
How should I run this project

### ISSUE THREAD

**Issue by Vanillaaa1** [IamOmaR22/eLearning-Website-with-Django-and-Python#16]
Hy can you please tell me after downloading zip file .. where and how should i run this project?!!

**Comment by IamOmaR22** [comment]
Do you know django?

**Comment by Vanillaaa1** [comment]
Yess

**Comment by IamOmaR22** [comment]
You can run this on your computer or can deploy this.

**Comment by Vanillaaa1** [comment]
After downloading zip file .. where should i open the file.. can u please tell me in steps

**Comment by IamOmaR22** [comment]
If you know django then you can do this.

01771844336
My whatsapp

**Comment by Vanillaaa1** [comment]
Okay
